var imgs = {
	title: './assets/images/title.png',
	play: './assets/images/play.png',
	logo: './assets/images/logo.png',
	share: './assets/images/share.png',
	bottom: './assets/images/bottom.png',
	camera: './assets/images/camera.png',
	camera1: './assets/images/camera1.png',
	camera2: './assets/images/camera2.png',
	sure: './assets/images/sure.png',
	wheel: './assets/images/wheel.png',
	play: './assets/images/play.png',
	img1: './assets/images/1.png',
	img2: './assets/images/2.png',
	img3: './assets/images/3.png',
	img4: './assets/images/4.png',
	img5: './assets/images/5.png',
	img6: './assets/images/6.png',
	img7: './assets/images/7.png',
	imgBg: './assets/images/img-bg.png',
	imgBg1: './assets/images/img-bg1.png',

	j1: './assets/images/j1.jpg',
	jbg1: './assets/images/j-bg1.jpg',
	jbg2: './assets/images/j-bg2.jpg',
	jbg21: './assets/images/j-bg2-1.jpg',
	jbg22: './assets/images/j-bg2-2.jpg',
	jbg3: './assets/images/j-bg3.jpg',
	jbg4: './assets/images/j-bg4.jpg',
	jbg5: './assets/images/j-bg5.jpg',
	hhh: './assets/images/hhh.jpg',
	line: './assets/images/line.jpg',
	back: './assets/images/back.png',
	microphone: './assets/images/microphone.jpg',
	download: './assets/images/download.png',
	hhhPoster: './assets/images/hhh-poster.jpg',

	copyright1: './assets/images/copyright-1.jpg'

}
export default imgs;